split R CMD check

diff --git a/.github/workflows/build-install-check.yaml b/.github/workflows/build-install-check.yaml
--- a/.github/workflows/build-install-check.yaml
+++ b/.github/workflows/build-install-check.yaml
@@ -46,12 +46,15 @@ jobs:
         shell: bash
 
       - name: Run R CMD CHECK
+        run: R CMD check --no-manual ${{ env.PKGBUILD }}
+        shell: bash
+
+      - name: No Errors No Warnings
         run: |
-          R CMD check --no-manual ${{ env.PKGBUILD }}
           result=$(tail -1 ${{ github.event.repository.name }}.Rcheck/00check.log)
-          [[ $result == Status:* ]] || echo "::debug::{could not get Status line}"; exit 1
-          [[ $result == *"Error"* ]] && echo "::debug::{checks results in errors}"; exit 1
-          [[ $result == *"WARNINGs"* ]] && echo "::debug::{checks results in warnings}"; exit 1
+          [[ $result == Status:* ]] || (echo "::debug::{could not get Status line}" && exit 1)
+          [[ $result == *"Error"* ]] && (echo "::debug::{checks results in errors}" && exit 1)
+          [[ $result == *"WARNINGs"* ]] && (echo "::debug::{checks results in warnings}" && exit 1)
         shell: bash
 
       - name: Install R package
